version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8000"

  frontend:
    build: ./frontend
    expose:
      - "80"

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend